server:
  host: "0.0.0.0"
  port: 8080
  grpc_port: 9090

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "aiwriter"
  sslmode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

minio:
  endpoint: "localhost:9000"
  accesskey: "minioadmin"
  secretkey: "minioadmin"
  usessl: false
  bucket: "aiwriter"

milvus:
  host: "localhost"
  port: 19530

log:
  level: "info"
  format: "json"
  output: "both"
  enablecaller: true
  enablestacktrace: true
  file:
    filename: "logs/app.log"
    maxsize: 100
    maxage: 30
    maxbackups: 10
    compress: true

mineru:
  base_url: "https://mineru.net"
  api_key: "eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJqdGkiOiI2MjEwMDIzMiIsInJvbCI6IlJPTEVfUkVHSVNURVIiLCJpc3MiOiJPcGVuWExhYiIsImlhdCI6MTc1ODAzNzU2MiwiY2xpZW50SWQiOiJsa3pkeDU3bnZ5MjJqa3BxOXgydyIsInBob25lIjoiIiwib3BlbklkIjpudWxsLCJ1dWlkIjoiYTJlOWUyNDQtYjJkZi00ZGQxLWFjMDYtZDMyYTk1MTNhMmU5IiwiZW1haWwiOiIiLCJleHAiOjE3NTkyNDcxNjJ9.iBbpX2Dr_dyR5x3tprCwS8aECebpHEeAG-tidD1rM6nwpOKE4ogr9Wn7sEkQSlQRk0_n9ng5ddJTpaCqJ1EiAg"
  timeout: 30s
  max_retries: 3
  default_language: "ch"
  enable_formula: true
  enable_table: true
  model_version: "pipeline"

auth:
  jwt_secret: "oyogames.cn"
  jwt_issuer: "ai-writer-backend"
  totp_issuer: "AI Writer"
  backup_codes: 8
