// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/auth/v1/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Register
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Login
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Require_2Fa   bool                   `protobuf:"varint,1,opt,name=require_2fa,json=require2fa,proto3" json:"require_2fa,omitempty"`
	PendingAuthId string                 `protobuf:"bytes,2,opt,name=pending_auth_id,json=pendingAuthId,proto3" json:"pending_auth_id,omitempty"` // 当 require_2fa=true 时返回，用于后续 2FA 验证
	Tokens        *TokenPair             `protobuf:"bytes,3,opt,name=tokens,proto3" json:"tokens,omitempty"`                                      // 当 require_2fa=false 时返回
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetRequire_2Fa() bool {
	if x != nil {
		return x.Require_2Fa
	}
	return false
}

func (x *LoginResponse) GetPendingAuthId() string {
	if x != nil {
		return x.PendingAuthId
	}
	return ""
}

func (x *LoginResponse) GetTokens() *TokenPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

// RefreshToken
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_api_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        *TokenPair             `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_api_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshTokenResponse) GetTokens() *TokenPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

// Enable2FA
type Enable2FARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enable2FARequest) Reset() {
	*x = Enable2FARequest{}
	mi := &file_api_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enable2FARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enable2FARequest) ProtoMessage() {}

func (x *Enable2FARequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enable2FARequest.ProtoReflect.Descriptor instead.
func (*Enable2FARequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *Enable2FARequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Enable2FAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Setup         *TwoFactorSetup        `protobuf:"bytes,1,opt,name=setup,proto3" json:"setup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enable2FAResponse) Reset() {
	*x = Enable2FAResponse{}
	mi := &file_api_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enable2FAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enable2FAResponse) ProtoMessage() {}

func (x *Enable2FAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enable2FAResponse.ProtoReflect.Descriptor instead.
func (*Enable2FAResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *Enable2FAResponse) GetSetup() *TwoFactorSetup {
	if x != nil {
		return x.Setup
	}
	return nil
}

// GetQRCode
type GetQRCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQRCodeRequest) Reset() {
	*x = GetQRCodeRequest{}
	mi := &file_api_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQRCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQRCodeRequest) ProtoMessage() {}

func (x *GetQRCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQRCodeRequest.ProtoReflect.Descriptor instead.
func (*GetQRCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *GetQRCodeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetQRCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QrCodeImage   []byte                 `protobuf:"bytes,1,opt,name=qr_code_image,json=qrCodeImage,proto3" json:"qr_code_image,omitempty"` // PNG image data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQRCodeResponse) Reset() {
	*x = GetQRCodeResponse{}
	mi := &file_api_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQRCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQRCodeResponse) ProtoMessage() {}

func (x *GetQRCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQRCodeResponse.ProtoReflect.Descriptor instead.
func (*GetQRCodeResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *GetQRCodeResponse) GetQrCodeImage() []byte {
	if x != nil {
		return x.QrCodeImage
	}
	return nil
}

// Confirm2FA
type Confirm2FARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Confirm2FARequest) Reset() {
	*x = Confirm2FARequest{}
	mi := &file_api_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Confirm2FARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirm2FARequest) ProtoMessage() {}

func (x *Confirm2FARequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirm2FARequest.ProtoReflect.Descriptor instead.
func (*Confirm2FARequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *Confirm2FARequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Confirm2FARequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Confirm2FAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Confirm2FAResponse) Reset() {
	*x = Confirm2FAResponse{}
	mi := &file_api_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Confirm2FAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirm2FAResponse) ProtoMessage() {}

func (x *Confirm2FAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirm2FAResponse.ProtoReflect.Descriptor instead.
func (*Confirm2FAResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *Confirm2FAResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Confirm2FAResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Verify2FA
type Verify2FARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PendingAuthId string                 `protobuf:"bytes,1,opt,name=pending_auth_id,json=pendingAuthId,proto3" json:"pending_auth_id,omitempty"` // 从 Login 返回的 pending_auth_id
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                                          // 6位 TOTP 验证码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verify2FARequest) Reset() {
	*x = Verify2FARequest{}
	mi := &file_api_auth_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verify2FARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verify2FARequest) ProtoMessage() {}

func (x *Verify2FARequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verify2FARequest.ProtoReflect.Descriptor instead.
func (*Verify2FARequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *Verify2FARequest) GetPendingAuthId() string {
	if x != nil {
		return x.PendingAuthId
	}
	return ""
}

func (x *Verify2FARequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Verify2FAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        *TokenPair             `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verify2FAResponse) Reset() {
	*x = Verify2FAResponse{}
	mi := &file_api_auth_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verify2FAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verify2FAResponse) ProtoMessage() {}

func (x *Verify2FAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verify2FAResponse.ProtoReflect.Descriptor instead.
func (*Verify2FAResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *Verify2FAResponse) GetTokens() *TokenPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

// Disable2FA
type Disable2FARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disable2FARequest) Reset() {
	*x = Disable2FARequest{}
	mi := &file_api_auth_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disable2FARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disable2FARequest) ProtoMessage() {}

func (x *Disable2FARequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disable2FARequest.ProtoReflect.Descriptor instead.
func (*Disable2FARequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *Disable2FARequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Disable2FARequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Disable2FAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disable2FAResponse) Reset() {
	*x = Disable2FAResponse{}
	mi := &file_api_auth_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disable2FAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disable2FAResponse) ProtoMessage() {}

func (x *Disable2FAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disable2FAResponse.ProtoReflect.Descriptor instead.
func (*Disable2FAResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_proto_rawDescGZIP(), []int{15}
}

func (x *Disable2FAResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Disable2FAResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_auth_v1_auth_proto protoreflect.FileDescriptor

const file_api_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x16api/auth/v1/auth.proto\x12\vapi.auth.v1\x1a\x17api/auth/v1/types.proto\"W\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"[\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x88\x01\n" +
	"\rLoginResponse\x12\x1f\n" +
	"\vrequire_2fa\x18\x01 \x01(\bR\n" +
	"require2fa\x12&\n" +
	"\x0fpending_auth_id\x18\x02 \x01(\tR\rpendingAuthId\x12.\n" +
	"\x06tokens\x18\x03 \x01(\v2\x16.api.auth.v1.TokenPairR\x06tokens\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"F\n" +
	"\x14RefreshTokenResponse\x12.\n" +
	"\x06tokens\x18\x01 \x01(\v2\x16.api.auth.v1.TokenPairR\x06tokens\"+\n" +
	"\x10Enable2FARequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"F\n" +
	"\x11Enable2FAResponse\x121\n" +
	"\x05setup\x18\x01 \x01(\v2\x1b.api.auth.v1.TwoFactorSetupR\x05setup\"+\n" +
	"\x10GetQRCodeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"7\n" +
	"\x11GetQRCodeResponse\x12\"\n" +
	"\rqr_code_image\x18\x01 \x01(\fR\vqrCodeImage\"@\n" +
	"\x11Confirm2FARequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"H\n" +
	"\x12Confirm2FAResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"N\n" +
	"\x10Verify2FARequest\x12&\n" +
	"\x0fpending_auth_id\x18\x01 \x01(\tR\rpendingAuthId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"C\n" +
	"\x11Verify2FAResponse\x12.\n" +
	"\x06tokens\x18\x01 \x01(\v2\x16.api.auth.v1.TokenPairR\x06tokens\"H\n" +
	"\x11Disable2FARequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"H\n" +
	"\x12Disable2FAResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xed\x04\n" +
	"\vAuthService\x12G\n" +
	"\bRegister\x12\x1c.api.auth.v1.RegisterRequest\x1a\x1d.api.auth.v1.RegisterResponse\x12>\n" +
	"\x05Login\x12\x19.api.auth.v1.LoginRequest\x1a\x1a.api.auth.v1.LoginResponse\x12S\n" +
	"\fRefreshToken\x12 .api.auth.v1.RefreshTokenRequest\x1a!.api.auth.v1.RefreshTokenResponse\x12J\n" +
	"\tEnable2FA\x12\x1d.api.auth.v1.Enable2FARequest\x1a\x1e.api.auth.v1.Enable2FAResponse\x12J\n" +
	"\tGetQRCode\x12\x1d.api.auth.v1.GetQRCodeRequest\x1a\x1e.api.auth.v1.GetQRCodeResponse\x12M\n" +
	"\n" +
	"Confirm2FA\x12\x1e.api.auth.v1.Confirm2FARequest\x1a\x1f.api.auth.v1.Confirm2FAResponse\x12J\n" +
	"\tVerify2FA\x12\x1d.api.auth.v1.Verify2FARequest\x1a\x1e.api.auth.v1.Verify2FAResponse\x12M\n" +
	"\n" +
	"Disable2FA\x12\x1e.api.auth.v1.Disable2FARequest\x1a\x1f.api.auth.v1.Disable2FAResponseB>Z<github.com/yourusername/ai-writer-backend/api/auth/v1;authv1b\x06proto3"

var (
	file_api_auth_v1_auth_proto_rawDescOnce sync.Once
	file_api_auth_v1_auth_proto_rawDescData []byte
)

func file_api_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_api_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_api_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auth_v1_auth_proto_rawDesc), len(file_api_auth_v1_auth_proto_rawDesc)))
	})
	return file_api_auth_v1_auth_proto_rawDescData
}

var file_api_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_auth_v1_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),      // 0: api.auth.v1.RegisterRequest
	(*RegisterResponse)(nil),     // 1: api.auth.v1.RegisterResponse
	(*LoginRequest)(nil),         // 2: api.auth.v1.LoginRequest
	(*LoginResponse)(nil),        // 3: api.auth.v1.LoginResponse
	(*RefreshTokenRequest)(nil),  // 4: api.auth.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil), // 5: api.auth.v1.RefreshTokenResponse
	(*Enable2FARequest)(nil),     // 6: api.auth.v1.Enable2FARequest
	(*Enable2FAResponse)(nil),    // 7: api.auth.v1.Enable2FAResponse
	(*GetQRCodeRequest)(nil),     // 8: api.auth.v1.GetQRCodeRequest
	(*GetQRCodeResponse)(nil),    // 9: api.auth.v1.GetQRCodeResponse
	(*Confirm2FARequest)(nil),    // 10: api.auth.v1.Confirm2FARequest
	(*Confirm2FAResponse)(nil),   // 11: api.auth.v1.Confirm2FAResponse
	(*Verify2FARequest)(nil),     // 12: api.auth.v1.Verify2FARequest
	(*Verify2FAResponse)(nil),    // 13: api.auth.v1.Verify2FAResponse
	(*Disable2FARequest)(nil),    // 14: api.auth.v1.Disable2FARequest
	(*Disable2FAResponse)(nil),   // 15: api.auth.v1.Disable2FAResponse
	(*TokenPair)(nil),            // 16: api.auth.v1.TokenPair
	(*TwoFactorSetup)(nil),       // 17: api.auth.v1.TwoFactorSetup
}
var file_api_auth_v1_auth_proto_depIdxs = []int32{
	16, // 0: api.auth.v1.LoginResponse.tokens:type_name -> api.auth.v1.TokenPair
	16, // 1: api.auth.v1.RefreshTokenResponse.tokens:type_name -> api.auth.v1.TokenPair
	17, // 2: api.auth.v1.Enable2FAResponse.setup:type_name -> api.auth.v1.TwoFactorSetup
	16, // 3: api.auth.v1.Verify2FAResponse.tokens:type_name -> api.auth.v1.TokenPair
	0,  // 4: api.auth.v1.AuthService.Register:input_type -> api.auth.v1.RegisterRequest
	2,  // 5: api.auth.v1.AuthService.Login:input_type -> api.auth.v1.LoginRequest
	4,  // 6: api.auth.v1.AuthService.RefreshToken:input_type -> api.auth.v1.RefreshTokenRequest
	6,  // 7: api.auth.v1.AuthService.Enable2FA:input_type -> api.auth.v1.Enable2FARequest
	8,  // 8: api.auth.v1.AuthService.GetQRCode:input_type -> api.auth.v1.GetQRCodeRequest
	10, // 9: api.auth.v1.AuthService.Confirm2FA:input_type -> api.auth.v1.Confirm2FARequest
	12, // 10: api.auth.v1.AuthService.Verify2FA:input_type -> api.auth.v1.Verify2FARequest
	14, // 11: api.auth.v1.AuthService.Disable2FA:input_type -> api.auth.v1.Disable2FARequest
	1,  // 12: api.auth.v1.AuthService.Register:output_type -> api.auth.v1.RegisterResponse
	3,  // 13: api.auth.v1.AuthService.Login:output_type -> api.auth.v1.LoginResponse
	5,  // 14: api.auth.v1.AuthService.RefreshToken:output_type -> api.auth.v1.RefreshTokenResponse
	7,  // 15: api.auth.v1.AuthService.Enable2FA:output_type -> api.auth.v1.Enable2FAResponse
	9,  // 16: api.auth.v1.AuthService.GetQRCode:output_type -> api.auth.v1.GetQRCodeResponse
	11, // 17: api.auth.v1.AuthService.Confirm2FA:output_type -> api.auth.v1.Confirm2FAResponse
	13, // 18: api.auth.v1.AuthService.Verify2FA:output_type -> api.auth.v1.Verify2FAResponse
	15, // 19: api.auth.v1.AuthService.Disable2FA:output_type -> api.auth.v1.Disable2FAResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_auth_v1_auth_proto_init() }
func file_api_auth_v1_auth_proto_init() {
	if File_api_auth_v1_auth_proto != nil {
		return
	}
	file_api_auth_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_auth_proto_rawDesc), len(file_api_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_api_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_api_auth_v1_auth_proto = out.File
	file_api_auth_v1_auth_proto_goTypes = nil
	file_api_auth_v1_auth_proto_depIdxs = nil
}
