// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/auth/v1/types.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User represents a user account
type User struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email               string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified       bool                   `protobuf:"varint,4,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	TwoFactorEnabled    bool                   `protobuf:"varint,5,opt,name=two_factor_enabled,json=twoFactorEnabled,proto3" json:"two_factor_enabled,omitempty"`
	LastLoginAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	LastLoginIp         string                 `protobuf:"bytes,7,opt,name=last_login_ip,json=lastLoginIp,proto3" json:"last_login_ip,omitempty"`
	FailedLoginAttempts int32                  `protobuf:"varint,8,opt,name=failed_login_attempts,json=failedLoginAttempts,proto3" json:"failed_login_attempts,omitempty"`
	LockedUntil         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=locked_until,json=lockedUntil,proto3" json:"locked_until,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_auth_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *User) GetTwoFactorEnabled() bool {
	if x != nil {
		return x.TwoFactorEnabled
	}
	return false
}

func (x *User) GetLastLoginAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginAt
	}
	return nil
}

func (x *User) GetLastLoginIp() string {
	if x != nil {
		return x.LastLoginIp
	}
	return ""
}

func (x *User) GetFailedLoginAttempts() int32 {
	if x != nil {
		return x.FailedLoginAttempts
	}
	return 0
}

func (x *User) GetLockedUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.LockedUntil
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// TokenPair represents access and refresh tokens
type TokenPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"` // seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPair) Reset() {
	*x = TokenPair{}
	mi := &file_api_auth_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPair) ProtoMessage() {}

func (x *TokenPair) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPair.ProtoReflect.Descriptor instead.
func (*TokenPair) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *TokenPair) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenPair) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenPair) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// TwoFactorSetup contains TOTP secret and backup codes
type TwoFactorSetup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	QrCodeUrl     string                 `protobuf:"bytes,2,opt,name=qr_code_url,json=qrCodeUrl,proto3" json:"qr_code_url,omitempty"`
	BackupCodes   []string               `protobuf:"bytes,3,rep,name=backup_codes,json=backupCodes,proto3" json:"backup_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwoFactorSetup) Reset() {
	*x = TwoFactorSetup{}
	mi := &file_api_auth_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwoFactorSetup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoFactorSetup) ProtoMessage() {}

func (x *TwoFactorSetup) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoFactorSetup.ProtoReflect.Descriptor instead.
func (*TwoFactorSetup) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *TwoFactorSetup) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *TwoFactorSetup) GetQrCodeUrl() string {
	if x != nil {
		return x.QrCodeUrl
	}
	return ""
}

func (x *TwoFactorSetup) GetBackupCodes() []string {
	if x != nil {
		return x.BackupCodes
	}
	return nil
}

var File_api_auth_v1_types_proto protoreflect.FileDescriptor

const file_api_auth_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x17api/auth/v1/types.proto\x12\vapi.auth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12%\n" +
	"\x0eemail_verified\x18\x04 \x01(\bR\remailVerified\x12,\n" +
	"\x12two_factor_enabled\x18\x05 \x01(\bR\x10twoFactorEnabled\x12>\n" +
	"\rlast_login_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vlastLoginAt\x12\"\n" +
	"\rlast_login_ip\x18\a \x01(\tR\vlastLoginIp\x122\n" +
	"\x15failed_login_attempts\x18\b \x01(\x05R\x13failedLoginAttempts\x12=\n" +
	"\flocked_until\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vlockedUntil\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"r\n" +
	"\tTokenPair\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\"k\n" +
	"\x0eTwoFactorSetup\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x1e\n" +
	"\vqr_code_url\x18\x02 \x01(\tR\tqrCodeUrl\x12!\n" +
	"\fbackup_codes\x18\x03 \x03(\tR\vbackupCodesB>Z<github.com/yourusername/ai-writer-backend/api/auth/v1;authv1b\x06proto3"

var (
	file_api_auth_v1_types_proto_rawDescOnce sync.Once
	file_api_auth_v1_types_proto_rawDescData []byte
)

func file_api_auth_v1_types_proto_rawDescGZIP() []byte {
	file_api_auth_v1_types_proto_rawDescOnce.Do(func() {
		file_api_auth_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auth_v1_types_proto_rawDesc), len(file_api_auth_v1_types_proto_rawDesc)))
	})
	return file_api_auth_v1_types_proto_rawDescData
}

var file_api_auth_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_auth_v1_types_proto_goTypes = []any{
	(*User)(nil),                  // 0: api.auth.v1.User
	(*TokenPair)(nil),             // 1: api.auth.v1.TokenPair
	(*TwoFactorSetup)(nil),        // 2: api.auth.v1.TwoFactorSetup
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_api_auth_v1_types_proto_depIdxs = []int32{
	3, // 0: api.auth.v1.User.last_login_at:type_name -> google.protobuf.Timestamp
	3, // 1: api.auth.v1.User.locked_until:type_name -> google.protobuf.Timestamp
	3, // 2: api.auth.v1.User.created_at:type_name -> google.protobuf.Timestamp
	3, // 3: api.auth.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_auth_v1_types_proto_init() }
func file_api_auth_v1_types_proto_init() {
	if File_api_auth_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_types_proto_rawDesc), len(file_api_auth_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_auth_v1_types_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_types_proto_depIdxs,
		MessageInfos:      file_api_auth_v1_types_proto_msgTypes,
	}.Build()
	File_api_auth_v1_types_proto = out.File
	file_api_auth_v1_types_proto_goTypes = nil
	file_api_auth_v1_types_proto_depIdxs = nil
}
